/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "api.pb-c.h"
void   create_key__init
                     (CreateKey         *message)
{
  static const CreateKey init_value = CREATE_KEY__INIT;
  *message = init_value;
}
size_t create_key__get_packed_size
                     (const CreateKey *message)
{
  assert(message->base.descriptor == &create_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_key__pack
                     (const CreateKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_key__pack_to_buffer
                     (const CreateKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateKey *
       create_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateKey *)
     protobuf_c_message_unpack (&create_key__descriptor,
                                allocator, len, data);
}
void   create_key__free_unpacked
                     (CreateKey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &create_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_key_resp__init
                     (CreateKeyResp         *message)
{
  static const CreateKeyResp init_value = CREATE_KEY_RESP__INIT;
  *message = init_value;
}
size_t create_key_resp__get_packed_size
                     (const CreateKeyResp *message)
{
  assert(message->base.descriptor == &create_key_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_key_resp__pack
                     (const CreateKeyResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_key_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_key_resp__pack_to_buffer
                     (const CreateKeyResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_key_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateKeyResp *
       create_key_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateKeyResp *)
     protobuf_c_message_unpack (&create_key_resp__descriptor,
                                allocator, len, data);
}
void   create_key_resp__free_unpacked
                     (CreateKeyResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &create_key_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sign_with_key__init
                     (SignWithKey         *message)
{
  static const SignWithKey init_value = SIGN_WITH_KEY__INIT;
  *message = init_value;
}
size_t sign_with_key__get_packed_size
                     (const SignWithKey *message)
{
  assert(message->base.descriptor == &sign_with_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sign_with_key__pack
                     (const SignWithKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sign_with_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sign_with_key__pack_to_buffer
                     (const SignWithKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sign_with_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SignWithKey *
       sign_with_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SignWithKey *)
     protobuf_c_message_unpack (&sign_with_key__descriptor,
                                allocator, len, data);
}
void   sign_with_key__free_unpacked
                     (SignWithKey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sign_with_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sign_with_key_resp__init
                     (SignWithKeyResp         *message)
{
  static const SignWithKeyResp init_value = SIGN_WITH_KEY_RESP__INIT;
  *message = init_value;
}
size_t sign_with_key_resp__get_packed_size
                     (const SignWithKeyResp *message)
{
  assert(message->base.descriptor == &sign_with_key_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sign_with_key_resp__pack
                     (const SignWithKeyResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sign_with_key_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sign_with_key_resp__pack_to_buffer
                     (const SignWithKeyResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sign_with_key_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SignWithKeyResp *
       sign_with_key_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SignWithKeyResp *)
     protobuf_c_message_unpack (&sign_with_key_resp__descriptor,
                                allocator, len, data);
}
void   sign_with_key_resp__free_unpacked
                     (SignWithKeyResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sign_with_key_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   delete_key__init
                     (DeleteKey         *message)
{
  static const DeleteKey init_value = DELETE_KEY__INIT;
  *message = init_value;
}
size_t delete_key__get_packed_size
                     (const DeleteKey *message)
{
  assert(message->base.descriptor == &delete_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t delete_key__pack
                     (const DeleteKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &delete_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t delete_key__pack_to_buffer
                     (const DeleteKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &delete_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeleteKey *
       delete_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeleteKey *)
     protobuf_c_message_unpack (&delete_key__descriptor,
                                allocator, len, data);
}
void   delete_key__free_unpacked
                     (DeleteKey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &delete_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   delete_key_resp__init
                     (DeleteKeyResp         *message)
{
  static const DeleteKeyResp init_value = DELETE_KEY_RESP__INIT;
  *message = init_value;
}
size_t delete_key_resp__get_packed_size
                     (const DeleteKeyResp *message)
{
  assert(message->base.descriptor == &delete_key_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t delete_key_resp__pack
                     (const DeleteKeyResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &delete_key_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t delete_key_resp__pack_to_buffer
                     (const DeleteKeyResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &delete_key_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DeleteKeyResp *
       delete_key_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DeleteKeyResp *)
     protobuf_c_message_unpack (&delete_key_resp__descriptor,
                                allocator, len, data);
}
void   delete_key_resp__free_unpacked
                     (DeleteKeyResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &delete_key_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   eve_request__init
                     (EveRequest         *message)
{
  static const EveRequest init_value = EVE_REQUEST__INIT;
  *message = init_value;
}
size_t eve_request__get_packed_size
                     (const EveRequest *message)
{
  assert(message->base.descriptor == &eve_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eve_request__pack
                     (const EveRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eve_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eve_request__pack_to_buffer
                     (const EveRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eve_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EveRequest *
       eve_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EveRequest *)
     protobuf_c_message_unpack (&eve_request__descriptor,
                                allocator, len, data);
}
void   eve_request__free_unpacked
                     (EveRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &eve_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   eve_response__init
                     (EveResponse         *message)
{
  static const EveResponse init_value = EVE_RESPONSE__INIT;
  *message = init_value;
}
size_t eve_response__get_packed_size
                     (const EveResponse *message)
{
  assert(message->base.descriptor == &eve_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t eve_response__pack
                     (const EveResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &eve_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t eve_response__pack_to_buffer
                     (const EveResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &eve_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EveResponse *
       eve_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EveResponse *)
     protobuf_c_message_unpack (&eve_response__descriptor,
                                allocator, len, data);
}
void   eve_response__free_unpacked
                     (EveResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &eve_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor create_key__field_descriptors[1] =
{
  {
    "algorithm",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateKey, algorithm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_key__field_indices_by_name[] = {
  0,   /* field[0] = algorithm */
};
static const ProtobufCIntRange create_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor create_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateKey",
  "CreateKey",
  "CreateKey",
  "",
  sizeof(CreateKey),
  1,
  create_key__field_descriptors,
  create_key__field_indices_by_name,
  1,  create_key__number_ranges,
  (ProtobufCMessageInit) create_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_key_resp__field_descriptors[3] =
{
  {
    "status_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateKeyResp, status_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key_handle",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateKeyResp, key_handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CreateKeyResp, error),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_key_resp__field_indices_by_name[] = {
  2,   /* field[2] = error */
  1,   /* field[1] = key_handle */
  0,   /* field[0] = status_code */
};
static const ProtobufCIntRange create_key_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor create_key_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateKeyResp",
  "CreateKeyResp",
  "CreateKeyResp",
  "",
  sizeof(CreateKeyResp),
  3,
  create_key_resp__field_descriptors,
  create_key_resp__field_indices_by_name,
  1,  create_key_resp__number_ranges,
  (ProtobufCMessageInit) create_key_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sign_with_key__field_descriptors[2] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SignWithKey, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key_handle",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SignWithKey, key_handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sign_with_key__field_indices_by_name[] = {
  1,   /* field[1] = key_handle */
  0,   /* field[0] = message */
};
static const ProtobufCIntRange sign_with_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sign_with_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SignWithKey",
  "SignWithKey",
  "SignWithKey",
  "",
  sizeof(SignWithKey),
  2,
  sign_with_key__field_descriptors,
  sign_with_key__field_indices_by_name,
  1,  sign_with_key__number_ranges,
  (ProtobufCMessageInit) sign_with_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sign_with_key_resp__field_descriptors[3] =
{
  {
    "status_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SignWithKeyResp, status_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SignWithKeyResp, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SignWithKeyResp, error),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sign_with_key_resp__field_indices_by_name[] = {
  2,   /* field[2] = error */
  1,   /* field[1] = signature */
  0,   /* field[0] = status_code */
};
static const ProtobufCIntRange sign_with_key_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sign_with_key_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SignWithKeyResp",
  "SignWithKeyResp",
  "SignWithKeyResp",
  "",
  sizeof(SignWithKeyResp),
  3,
  sign_with_key_resp__field_descriptors,
  sign_with_key_resp__field_indices_by_name,
  1,  sign_with_key_resp__number_ranges,
  (ProtobufCMessageInit) sign_with_key_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor delete_key__field_descriptors[1] =
{
  {
    "key_handle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeleteKey, key_handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned delete_key__field_indices_by_name[] = {
  0,   /* field[0] = key_handle */
};
static const ProtobufCIntRange delete_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor delete_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeleteKey",
  "DeleteKey",
  "DeleteKey",
  "",
  sizeof(DeleteKey),
  1,
  delete_key__field_descriptors,
  delete_key__field_indices_by_name,
  1,  delete_key__number_ranges,
  (ProtobufCMessageInit) delete_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor delete_key_resp__field_descriptors[2] =
{
  {
    "status_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DeleteKeyResp, status_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DeleteKeyResp, error),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned delete_key_resp__field_indices_by_name[] = {
  1,   /* field[1] = error */
  0,   /* field[0] = status_code */
};
static const ProtobufCIntRange delete_key_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor delete_key_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DeleteKeyResp",
  "DeleteKeyResp",
  "DeleteKeyResp",
  "",
  sizeof(DeleteKeyResp),
  2,
  delete_key_resp__field_descriptors,
  delete_key_resp__field_indices_by_name,
  1,  delete_key_resp__number_ranges,
  (ProtobufCMessageInit) delete_key_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor eve_request__field_descriptors[4] =
{
  {
    "message_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EveRequest, message_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EveRequest, create_key),
    &create_key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sign_with_key",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EveRequest, sign_with_key),
    &sign_with_key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_key",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EveRequest, delete_key),
    &delete_key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eve_request__field_indices_by_name[] = {
  1,   /* field[1] = create_key */
  3,   /* field[3] = delete_key */
  0,   /* field[0] = message_type */
  2,   /* field[2] = sign_with_key */
};
static const ProtobufCIntRange eve_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor eve_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EveRequest",
  "EveRequest",
  "EveRequest",
  "",
  sizeof(EveRequest),
  4,
  eve_request__field_descriptors,
  eve_request__field_indices_by_name,
  1,  eve_request__number_ranges,
  (ProtobufCMessageInit) eve_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor eve_response__field_descriptors[4] =
{
  {
    "message_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EveResponse, message_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_key_resp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EveResponse, create_key_resp),
    &create_key_resp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sign_with_key_resp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EveResponse, sign_with_key_resp),
    &sign_with_key_resp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delete_key_resp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EveResponse, delete_key_resp),
    &delete_key_resp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned eve_response__field_indices_by_name[] = {
  1,   /* field[1] = create_key_resp */
  3,   /* field[3] = delete_key_resp */
  0,   /* field[0] = message_type */
  2,   /* field[2] = sign_with_key_resp */
};
static const ProtobufCIntRange eve_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor eve_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EveResponse",
  "EveResponse",
  "EveResponse",
  "",
  sizeof(EveResponse),
  4,
  eve_response__field_descriptors,
  eve_response__field_indices_by_name,
  1,  eve_response__number_ranges,
  (ProtobufCMessageInit) eve_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
